### ISSUE TITLE
customizable shortcuts needed

### ISSUE THREAD

**Issue by s1ww** [octalmage/mDesktop#27]
in some games we use shortcuts such alt + number, so there are conflicts... we cant even turn off those hardcoded keybindings in mDesktop settings

custom keybindings much needed

I am using ctrl + alt + arrow keys in linux to navigate right, down, left, up desktops, i would be very happy to do so in windows too

**Comment by octalmage** [comment]
Thanks for the suggestion, this is something I'm already working on in #1. 

Sorry for the issues.

**Comment by s1ww** [comment]
great work. Lightweight decided to choose your product, its better than windows one.

**Comment by octalmage** [comment]
Thanks! Glad you like it!
