### ISSUE TITLE
Your software does not "slide". It juste switch without effect :(

### ISSUE THREAD

**Issue by Fr3d3r1ck** [octalmage/mDesktop#28]
I wanted a program to manage different office with effect "slide" but your program does not include this. If I refer to your demo on your website: http://getmdesktop.com/

I can therefore be considered that you are doing false advertising.

Fortunately I have not paid more than euro

**Comment by octalmage** [comment]
My apologies! I never considered someone would think that, I just used the Twitter Bootstap Slider to demonstrate the concept of desktop switching. The app also isn't a webpage or written in HTML.

This is the first complaint in over two years but I'll gladly refund your money and add a disclaimer. Email me your paypal email (email on my profile)! 

Thanks!

**Comment by Fr3d3r1ck** [comment]
I will not cry for one euro. As you said so well, leave a message to users
that they understand they will not display the bootstrap effect.

2015-04-11 1:47 GMT+02:00 Jason Stallings <notifications@github.com>:
