### ISSUE TITLE
getmdesktop.com is down

### ISSUE THREAD

**Issue by geekf** [octalmage/mDesktop#30]
Checked to ensure that is not down just for me.

http://downforeveryoneorjustme.com/getmdesktop.com

**Comment by octalmage** [comment]
Sorry about that! We're good now.

**Comment by TheThirdOne** [comment]
Its down again.

**Comment by octalmage** [comment]
It will be back up in a minute!

**Comment by HamboBlank** [comment]
Hi, the website has been down for several days.
