### ISSUE TITLE
Windows Unrecoverable after mDesktop crash

### ISSUE THREAD

**Issue by ClintJCL** [octalmage/mDesktop#32]
I had some stuff in 4 different windows.

mDesktop crashed.

I restart mDesktop.

Everything that is not in window 1 is completely inaccessible.

The process is running.  But the window?  Gone, gone, gone.

**Comment by mzomparelli** [comment]
@ClintJCL Ditch this app and use a better one.

https://github.com/mzomparelli/zVirtualDesktop

**Comment by ClintJCL** [comment]
@mzomparelli Thanks! I use Windows 7, and that zVirtualDesktop advertises itself as Windows 10 software. Do you know if it also works for Windows 7?

**Comment by mzomparelli** [comment]
It only works on Windows 10. If you want the best virtual desktop experience then use Windows 10 and zVirtualDesktop.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by octalmage** [comment]
mDesktop will attempt to recover the windows on re-open. It keeps a list of all windows on disk. If this happens again give this a try. 

@mzomparelli if you're not going to attempt to provide support, please don't post here. Thanks.
