### ISSUE TITLE
This app isn't updated, Use this one instead - zVirtualDesktop

### ISSUE THREAD

**Issue by mzomparelli** [octalmage/mDesktop#33]
https://github.com/mzomparelli/zVirtualDesktop

This uses the default Windows 10 Virtual Desktops. No need to reinvent the wheel. It's packed with features like different wallpaper on each desktop, hotkeys to navigate, move, and move & follow, and over 10 different icon sets to choose from. Another great feature is the ability to move all windows to a specific desktop. Also, why use AutoHotkey for this? That's not user-friendly. AHK is for more advanced users.

**Comment by KSSea** [comment]
Too bad zVirtualDesktop doesn't run on Windows 8.1 :-(  

This app is really good except for the z-order bug.  Every time I switch between desktops the ordering of apps on the taskbar gets scrambled :-(
